### ISSUE TITLE
work-queue empty?

### ISSUE THREAD

**Issue by SimonLab** [nelsonic/arana#39]
From my understanding it seems that the program will try to get the [next task/url](https://github.com/nelsonic/arana/blob/22cbe47b1a915b168da360f8640fb849ad6abd1a/lib/work_queue.js#L73) from the work-queue even if this sorted set is empty (although the chance to have an empty list is small as the program add constantly new urls). So my question is what happen if the work-queue set is empty?

**Comment by nelsonic** [comment]
@SimonLab if the `work-queue` is _empty_ the script should stop running.
But because the `work-queue` grows _exponentially_ (_each page that is visited has an average of 2 links follow_) this should not occur.

**Comment by SimonLab** [comment]
ok thanks
